# Generated by Django 3.1.4 on 2021-05-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210521_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
